// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.OracleDb.Configurations;

public  class SecGroupControlConfiguration : BaseConfiguration<SecGroupControl>
{
    public override void Configure(EntityTypeBuilder<SecGroupControl> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_GROUPS_CONTROLS table for linking groups and controls");

        entity.HasIndex(e => new { e.GroupCode, e.ControlId,e.PageCode })
        .IsUnique().HasFilter("is_deleted = FALSE"); ;

        entity.Property(e => e.ControlId).HasComment("Control code, foreign key referencing SEC_CONTROLS_LIST");

        entity.Property(e => e.GroupCode).HasComment("Group code, foreign key referencing SEC_GROUPS");

        entity.HasOne(d => d.SecControlLists)
            .WithMany(p => p.SecGroupControls)
            .HasForeignKey(d => d.ControlId)
            .OnDelete(DeleteBehavior.Restrict);

        entity.HasOne(d => d.SecPage)
            .WithMany(p => p.SecGroupControls)
            .HasForeignKey(d => d.PageCode)
            .OnDelete(DeleteBehavior.Restrict);

        entity.HasOne(d => d.SecGroups)
            .WithMany(p => p.SecGroupControls)
            .HasForeignKey(d => d.GroupCode)
            .OnDelete(DeleteBehavior.Restrict);

    }

}
