// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.OracleDb.Configurations;

public  class SecModuleConfiguration : BaseConfiguration<SecModule>
{
    public override void Configure(EntityTypeBuilder<SecModule> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_MODULES table for storing module information");


        entity.Property(e => e.ModuleName)
            .HasMaxLength(200)
            .HasComment("Name of the module");
        entity.Property(e => e.Icon)
            .HasMaxLength(50)
            .HasComment("Icon of the module");

        entity.Property(e => e.Color)
            .HasMaxLength(50)
            .HasComment("Color of the module");
        entity.Property(e => e.IsTaken)
        .HasDefaultValue(false);
        entity.HasData(
                 new SecModule { Id = 40, ModuleName = "التأمين والسرية", IsTaken = true },
                 new SecModule { Id = 41, ModuleName = "الموارد البشرية", IsTaken = true },
                 new SecModule { Id = 43, ModuleName = "التكويد", IsTaken = true },
                 new SecModule { Id = 44, ModuleName = "الأرشيف", IsTaken = true },
                 new SecModule {Id = 45, ModuleName = "المخازن", IsTaken = true },
                 new SecModule {Id = 46, ModuleName = "خدمة العملاء", IsTaken = true },
                 new SecModule {Id = 47, ModuleName = "المالى", IsTaken = true },
                 new SecModule {Id = 48, ModuleName = "التدريب", IsTaken = true },
                 new SecModule {Id = 49, ModuleName = "العقود والمشتروات", IsTaken = true }
                    );
    }

}
