// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.OracleDb.Configurations;

public  class SecServiceConfiguration : BaseConfiguration<SecService>
{
    public override void Configure(EntityTypeBuilder<SecService> entity)
    {
        base.Configure(entity);


        entity.HasComment("SEC_SERVICES table for storing SERVICES information");



        entity.Property(e => e.ServiceName)
            .HasMaxLength(200)
            .HasComment("Name of the SERVICES ");
        entity.Property(e => e.IsTaken)
        .HasDefaultValue(false);
        entity.HasOne(d => d.SecModules)
            .WithMany(p => p.SecServices)
            .HasForeignKey(d => d.ModuleNo).OnDelete(DeleteBehavior.Restrict);

    }

}
