// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.OracleDb.Configurations;

public partial class UserConfiguration : BaseConfiguration<User>
{
    public override void Configure(EntityTypeBuilder<User> entity)
    {
        base.Configure(entity);

        entity.HasComment("USERS table for storing user information");

        entity.HasIndex(e => e.UserName, "USER_NAME_UNIQUE")
            .IsUnique();

        entity.HasIndex(e => e.UserName, "USER_NAME_UNIQUE_INDEX")
            .IsUnique();



        entity.Property(e => e.EmpSerial).HasComment("Employee serial number associated with the user");

        entity.Property(e => e.Memo)
            .HasMaxLength(255)
            .HasComment("Additional notes or memo for the user");

        entity.Property(e => e.MtgPersonRole).HasComment("Role of the person in meetings");

        entity.Property(e => e.MtgRelPrsn)
            .HasMaxLength(200)
            .HasComment("Related person information for meetings");

        entity.Property(e => e.PersonCode)
            .HasMaxLength(20)
            .HasComment("Code associated with the person");

        entity.Property(e => e.Sign)
            .HasMaxLength(50)
            .HasComment("Digital signature of the user");

        entity.Property(e => e.Signotech)
            .HasDefaultValueSql("0")
            .HasComment("Flag for Signotec (default: 0)");

        entity.Property(e => e.UserActivation)
            .HasDefaultValueSql("1")
            .HasComment("Activation status of the user (default: 1)");

        entity.Property(e => e.UserDesc)
            .HasMaxLength(50)
            .HasComment("Description of the user");

        entity.Property(e => e.UserName)
            .HasMaxLength(50)
            .HasComment("Name of the user");

        entity.Property(e => e.UserPassword)
            .HasMaxLength(500)
            .HasComment("Encrypted password for the user");

        entity.Property(e => e.VersionNo).HasComment("Version number for the user");
        entity.Property(e => e.Sign).HasDefaultValue("empty");

    }

}
