// <auto-generated />
using System;
using Entities.Models.Databases.OracleDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Entities.Migrations.Oracle
{
    [DbContext(typeof(OracleContext))]
    partial class OracleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Tables.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Changes")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CHANGES");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<string>("EmpSerial")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("EMP_SERIAL");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<decimal?>("ModuleNo")
                        .HasPrecision(5)
                        .HasColumnType("DECIMAL(5)")
                        .HasColumnName("MODULE_NO");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TABLE_ID");

                    b.Property<string>("TableName")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TABLE_NAME");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("TIME_STAMP");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_AUDIT_LOGS");

                    b.ToTable("AUDIT_LOGS", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CONTROL_CODE")
                        .HasComment("Name of the control");

                    b.Property<string>("ControlDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CONTROL_DESCRIPTION")
                        .HasComment("Description of the control");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int>("PageId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PAGE_ID")
                        .HasComment("Foreign key referencing SEC_PAGES table");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_CONTROL_LISTS");

                    b.HasIndex("ControlCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_CONTROL_LISTS_CONTROL_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.HasIndex("PageId")
                        .HasDatabaseName("IX_SEC_CONTROL_LISTS_PAGE_ID");

                    b.ToTable("SEC_CONTROL_LISTS", null, t =>
                        {
                            t.HasComment("SEC_CONTROLS_LIST table for storing control information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveRole")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ARCHIVE_ROLE")
                        .HasComment("Role for archive permissions");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("GROUP_NAME")
                        .HasComment("Name of the group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_GROUPS");

                    b.ToTable("SEC_GROUPS", null, t =>
                        {
                            t.HasComment("SEC_GROUPS table for storing group information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ControlId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CONTROL_ID")
                        .HasComment("Control code, foreign key referencing SEC_CONTROLS_LIST");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("GroupCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GROUP_CODE")
                        .HasComment("Group code, foreign key referencing SEC_GROUPS");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int>("PageCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PAGE_CODE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_GROUP_CONTROLS");

                    b.HasIndex("ControlId")
                        .HasDatabaseName("IX_SEC_GROUP_CONTROLS_CONTROL_ID");

                    b.HasIndex("PageCode")
                        .HasDatabaseName("IX_SEC_GROUP_CONTROLS_PAGE_CODE");

                    b.HasIndex("GroupCode", "ControlId", "PageCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_GROUP_CONTROLS_GROUP_CODE_CONTROL_ID_PAGE_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_GROUP_CONTROLS", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_CONTROLS table for linking groups and controls");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("EmpCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_CODE")
                        .HasComment("Employee code referencing an employee");

                    b.Property<int>("GroupCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GROUP_CODE")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_GROUP_EMPLOYEES");

                    b.HasIndex("GroupCode", "EmpCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_GROUP_EMPLOYEES_GROUP_CODE_EMP_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_GROUP_EMPLOYEES", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_EMPLOYEES table for linking groups and employees");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("GroupCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GROUP_CODE")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int>("JobCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("JOB_CODE")
                        .HasComment("Job code referencing a job");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_GROUP_JOBS");

                    b.HasIndex("GroupCode", "JobCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_GROUP_JOBS_GROUP_CODE_JOB_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_GROUP_JOBS", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_JOBS table for linking groups and jobs");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("GroupCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GROUP_CODE")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int>("PageCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PAGE_CODE")
                        .HasComment("Page ID referencing a page");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_GROUP_PAGES");

                    b.HasIndex("PageCode")
                        .HasDatabaseName("IX_SEC_GROUP_PAGES_PAGE_CODE");

                    b.HasIndex("GroupCode", "PageCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_GROUP_PAGES_GROUP_CODE_PAGE_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_GROUP_PAGES", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_PAGES table for linking groups and pages");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("COLOR")
                        .HasComment("Color of the module");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ICON")
                        .HasComment("Icon of the module");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int?>("IsTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1,0)")
                        .HasDefaultValue(0)
                        .HasColumnName("IS_TAKEN");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MODULE_NAME")
                        .HasComment("Name of the module");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_MODULES");

                    b.ToTable("SEC_MODULES", null, t =>
                        {
                            t.HasComment("SEC_MODULES table for storing module information");
                        });

                    b.HasData(
                        new
                        {
                            Id = 40,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "التأمين والسرية"
                        },
                        new
                        {
                            Id = 41,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "الموارد البشرية"
                        },
                        new
                        {
                            Id = 43,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "التكويد"
                        },
                        new
                        {
                            Id = 44,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "الأرشيف"
                        },
                        new
                        {
                            Id = 45,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "المخازن"
                        },
                        new
                        {
                            Id = 46,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "خدمة العملاء"
                        },
                        new
                        {
                            Id = 47,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "المالى"
                        },
                        new
                        {
                            Id = 48,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "التدريب"
                        },
                        new
                        {
                            Id = 49,
                            IsDeleted = 0,
                            IsTaken = 1,
                            ModuleName = "العقود والمشتروات"
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModuleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("GroupCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GROUP_CODE");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODULE_CODE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_MODULE_GROUPS");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("IX_SEC_MODULE_GROUPS_MODULE_CODE");

                    b.HasIndex("GroupCode", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_MODULE_GROUPS_GROUP_CODE_MODULE_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_MODULE_GROUPS", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ICON")
                        .HasComment("Icon associated with the page");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODULE_CODE")
                        .HasComment("Module number associated with the page");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PAGE_NAME")
                        .HasComment("Page name in English");

                    b.Property<int>("PageOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PAGE_ORDER")
                        .HasComment("Order of the page");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("PAGE_URL")
                        .HasComment("Url associated with the page");

                    b.Property<int?>("ParentId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARENT_ID");

                    b.Property<int?>("ServiceCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SERVICE_CODE");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_PAGES");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("IX_SEC_PAGES_MODULE_CODE");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_SEC_PAGES_PARENT_ID");

                    b.HasIndex("ServiceCode")
                        .HasDatabaseName("IX_SEC_PAGES_SERVICE_CODE");

                    b.HasIndex("PageOrder", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("IX_SEC_PAGES_PAGE_ORDER_MODULE_CODE")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("SEC_PAGES", null, t =>
                        {
                            t.HasComment("SEC_PAGES table for storing page details");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<int?>("IsTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1,0)")
                        .HasDefaultValue(0)
                        .HasColumnName("IS_TAKEN");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<int?>("ModuleNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODULE_NO");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("SERVICE_NAME")
                        .HasComment("Name of the SERVICES ");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SEC_SERVICES");

                    b.HasIndex("ModuleNo")
                        .HasDatabaseName("IX_SEC_SERVICES_MODULE_NO");

                    b.ToTable("SEC_SERVICES", null, t =>
                        {
                            t.HasComment("SEC_SERVICES table for storing SERVICES information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("SignatureColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SIGNATURE_COLOR");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.HasKey("Id")
                        .HasName("PK_SIGNATURES");

                    b.ToTable("SIGNATURES", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELETE_DATE");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DELETE_USER_CODE");

                    b.Property<int?>("EmpSerial")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_SERIAL")
                        .HasComment("Employee serial number associated with the user");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_DATE");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("INSERT_USER_CODE");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("NUMBER(1,0)")
                        .HasColumnName("IS_DELETED");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LAST_UPDATE");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("MEMO")
                        .HasComment("Additional notes or memo for the user");

                    b.Property<int?>("MtgPersonRole")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MTG_PERSON_ROLE")
                        .HasComment("Role of the person in meetings");

                    b.Property<string>("MtgRelPrsn")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("MTG_REL_PRSN")
                        .HasComment("Related person information for meetings");

                    b.Property<string>("PersonCode")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PERSON_CODE")
                        .HasComment("Code associated with the person");

                    b.Property<string>("Sign")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasDefaultValue("empty")
                        .HasColumnName("SIGN")
                        .HasComment("Digital signature of the user");

                    b.Property<int?>("Signotech")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SIGNOTECH")
                        .HasDefaultValueSql("0")
                        .HasComment("Flag for Signotec (default: 0)");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UPDATE_USER_CODE");

                    b.Property<int?>("UserActivation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ACTIVATION")
                        .HasDefaultValueSql("1")
                        .HasComment("Activation status of the user (default: 1)");

                    b.Property<string>("UserDesc")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USER_DESC")
                        .HasComment("Description of the user");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USER_NAME")
                        .HasComment("Name of the user");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("USER_PASSWORD")
                        .HasComment("Encrypted password for the user");

                    b.Property<int?>("VersionNo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VERSION_NO")
                        .HasComment("Version number for the user");

                    b.HasKey("Id")
                        .HasName("PK_USERS");

                    b.HasIndex(new[] { "UserName" }, "USER_NAME_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_USER_NAME");

                    b.HasIndex(new[] { "UserName" }, "USER_NAME_UNIQUE_INDEX")
                        .IsUnique()
                        .HasDatabaseName("IX_USERS_USER_NAME");

                    b.ToTable("USERS", null, t =>
                        {
                            t.HasComment("USERS table for storing user information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecControlLists")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_CONTROL_LISTS_SEC_PAGES_PAGE_ID");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupControl", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecControlList", "SecControlLists")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_CONTROLS_SEC_CONTROL_LISTS_CONTROL_ID");

                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroups")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_CONTROLS_SEC_GROUPS_GROUP_CODE");

                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_CONTROLS_SEC_PAGES_PAGE_CODE");

                    b.Navigation("SecControlLists");

                    b.Navigation("SecGroups");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupEmployee", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecGroupEmployees")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_EMPLOYEES_SEC_GROUPS_GROUP_CODE");

                    b.Navigation("SecGroup");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupJob", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroups")
                        .WithMany("SecGroupJobs")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_JOBS_SEC_GROUPS_GROUP_CODE");

                    b.Navigation("SecGroups");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupPage", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecGroupPages")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_PAGES_SEC_GROUPS_GROUP_CODE");

                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecGroupPages")
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_GROUP_PAGES_SEC_PAGES_PAGE_CODE");

                    b.Navigation("SecGroup");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModuleGroup", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecModuleGroups")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_MODULE_GROUPS_SEC_GROUPS_GROUP_CODE");

                    b.HasOne("Entities.Models.Tables.SecModule", "SecModule")
                        .WithMany("SecModuleGroups")
                        .HasForeignKey("ModuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_MODULE_GROUPS_SEC_MODULES_MODULE_CODE");

                    b.Navigation("SecGroup");

                    b.Navigation("SecModule");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecModule", "SecModule")
                        .WithMany("SecPages")
                        .HasForeignKey("ModuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SEC_PAGES_SEC_MODULES_MODULE_CODE");

                    b.HasOne("Entities.Models.Tables.SecPage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SEC_PAGES_SEC_PAGES_PARENT_ID");

                    b.HasOne("Entities.Models.Tables.SecService", "SecService")
                        .WithMany("SecPages")
                        .HasForeignKey("ServiceCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_SEC_PAGES_SEC_SERVICES_SERVICE_CODE");

                    b.Navigation("Parent");

                    b.Navigation("SecModule");

                    b.Navigation("SecService");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecModule", "SecModules")
                        .WithMany("SecServices")
                        .HasForeignKey("ModuleNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SEC_SERVICES_SEC_MODULES_MODULE_NO");

                    b.Navigation("SecModules");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.Navigation("SecGroupControls");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroup", b =>
                {
                    b.Navigation("SecGroupControls");

                    b.Navigation("SecGroupEmployees");

                    b.Navigation("SecGroupJobs");

                    b.Navigation("SecGroupPages");

                    b.Navigation("SecModuleGroups");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModule", b =>
                {
                    b.Navigation("SecModuleGroups");

                    b.Navigation("SecPages");

                    b.Navigation("SecServices");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SecControlLists");

                    b.Navigation("SecGroupControls");

                    b.Navigation("SecGroupPages");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.Navigation("SecPages");
                });
#pragma warning restore 612, 618
        }
    }
}
