// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;


namespace Entities.Models.Tables;

public partial class AuditLog:BaseTable
{
    public string TableId { get; set; } = null!;
    public DateTime? TimeStamp { get; set; }
    public string? EmpSerial { get; set; }
    public string? TableName { get; set; }
    public string? Changes { get; set; }
    public decimal? ModuleNo { get; set; }
}