// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_CONTROLS_LIST table for storing control information
/// </summary>
public partial class SecControlList : BaseTable
{
    public SecControlList()
    {
        SecGroupControls = new HashSet<SecGroupControl>();
    }


    public string ControlCode { get; set; } = null!;
    public string ControlDescription { get; set; } = null!;
    public int PageId { get; set; }

    public virtual SecPage SecPage { get; set; } = null!;
    public virtual ICollection<SecGroupControl> SecGroupControls { get; set; }
}