// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;


public  class SecGroup:BaseTable
{
    public SecGroup()
    {
        SecGroupControls = new HashSet<SecGroupControl>();
        SecGroupJobs = new HashSet<SecGroupJob>();
        SecGroupPages = new HashSet<SecGroupPage>();
        SecModuleGroups = new HashSet<SecModuleGroup>();
        SecGroupEmployees = new HashSet<SecGroupEmployee>();
    }

    public string GroupName { get; set; }

    //public string? UnitCode { get; set; }
    public int? ArchiveRole { get; set; }

    public virtual ICollection<SecGroupControl> SecGroupControls { get; set; }
    public virtual ICollection<SecGroupJob> SecGroupJobs { get; set; }
    public virtual ICollection<SecModuleGroup> SecModuleGroups { get; set; }
    public virtual ICollection<SecGroupPage> SecGroupPages { get; set; }
    public virtual ICollection<SecGroupEmployee> SecGroupEmployees { get; set; }
}



