// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_GROUPS_EMPLOYEES table for linking groups and employees
/// </summary>
public  class SecGroupEmployee:BaseTable
{

    public int GroupCode { get; set; }

    public int EmpCode { get; set; }

    public virtual SecGroup SecGroup { get; set; }  

}