// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_GROUPS_PAGES table for linking groups and pages
/// </summary>
public  class SecGroupPage :BaseTable
{

    public int GroupCode { get; set; }
    public int PageCode { get; set; }

    public virtual SecGroup SecGroup { get; set; } = null!;
    public virtual SecPage SecPage { get; set; } = null!;
}