// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_GROUPS_JOBS table for linking groups and jobs
/// </summary>
public  class SecGroupJob:BaseTable
{
    /// <summary>
    /// Group code referencing a group
    /// </summary>
    public int GroupCode { get; set; }
    /// <summary>
    /// Job code referencing a job
    /// </summary>
    public int JobCode { get; set; }
    /// <summary>
    /// Unique identifier for the group-job relationship, auto-generated as identity
    /// </summary>
    //public int G_J_CODE { get; set; }

    public virtual SecGroup SecGroups { get; set; } = null!;
}