// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_GROUPS_CONTROLS table for linking groups and controls
/// </summary>
public  class SecGroupControl:BaseTable
{

    public int ControlId { get; set; }

    public int GroupCode { get; set; }
    public int PageCode { get; set; }


    public virtual SecControlList SecControlLists { get; set; } = null!;
    public virtual SecGroup SecGroups { get; set; } = null!;
    public virtual SecPage SecPage { get; set; } = null!;
}