// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_MODULES table for storing module information
/// </summary>
public  class SecModule:BaseTable
{
    public SecModule()
    {
        SecServices = new HashSet<SecService>();
        SecModuleGroups = new HashSet<SecModuleGroup>();
        SecPages = new HashSet<SecPage>();
    }

    public string ModuleName { get; set; } = null!;
    public string? Icon { get; set; }
    public string? Color { get; set; }
    public bool? IsTaken { get; set; }

    public virtual ICollection<SecModuleGroup> SecModuleGroups { get; set; }
    public virtual ICollection<SecPage> SecPages { get; set; }
    public virtual ICollection<SecService> SecServices { get; set; }
}