// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// SEC_PAGES table for storing page details
/// </summary>
public  class SecPage:BaseTable
{
    public SecPage()
    {
        SecControlLists = new HashSet<SecControlList>();
        SecGroupPages = new HashSet<SecGroupPage>();
        SecGroupControls = new HashSet<SecGroupControl>();
        Children = new HashSet<SecPage>();

    }


    public string PageName { get; set; }
    public int? ParentId { get; set; }
    public int PageOrder { get; set; }
    public string PageUrl { get; set; }
    public string? Icon { get; set; }
    public int ModuleCode { get; set; }
    public int? ServiceCode { get; set; }


    public virtual ICollection<SecControlList> SecControlLists { get; set; }
    public virtual ICollection<SecGroupControl> SecGroupControls { get; set; }
    public virtual ICollection<SecGroupPage> SecGroupPages { get; set; }
    public virtual ICollection<SecPage> Children { get; set; }
    public virtual SecPage? Parent { get; set; }
    public virtual SecModule? SecModule { get; set; }
    public virtual SecService? SecService { get; set; }
}

