// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables
{
    /// <summary>
    /// SEC_SERVICES table for storing SERVICES information
    /// </summary>
    public  class SecService:BaseTable
    {

        public int? ModuleNo { get; set; }
        public string ServiceName { get; set; } = null!;
        public bool? IsTaken { get; set; }

        public virtual SecModule? SecModules { get; set; }
        public virtual ICollection<SecPage> SecPages { get; set; }

    }
}