// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Entities.Models.BaseTables;
using Entities.Models.Tables;


namespace Entities.Models.Tables;

/// <summary>
/// USERS table for storing user information
/// </summary>
public  class User:BaseTable
{
    /// <summary>
    /// Unique code for the user, auto-generated as identity
    /// </summary>
    //public int USER_CODE { get; set; }
    /// <summary>
    /// Name of the user
    /// </summary>
    public string UserName { get; set; } = null!;
    /// <summary>
    /// Encrypted password for the user
    /// </summary>
    public string UserPassword { get; set; } = null!;
    /// <summary>
    /// Description of the user
    /// </summary>
    public string? UserDesc { get; set; }
    /// <summary>
    /// Code associated with the person
    /// </summary>
    public string? PersonCode { get; set; }
    /// <summary>
    /// Additional notes or memo for the user
    /// </summary>
    public string? Memo { get; set; }
    /// <summary>
    /// Role of the person in meetings
    /// </summary>
    public int? MtgPersonRole { get; set; }
    /// <summary>
    /// Related person information for meetings
    /// </summary>
    public string? MtgRelPrsn { get; set; }
    /// <summary>
    /// Activation status of the user (default: 1)
    /// </summary>
    public int? UserActivation { get; set; }
    /// <summary>
    /// Version number for the user
    /// </summary>
    public int? VersionNo { get; set; }
    /// <summary>
    /// Digital signature of the user
    /// </summary>
    public string? Sign { get; set; }
    /// <summary>
    /// Flag for Signotec (default: 0)
    /// </summary>
    public int? Signotech { get; set; }
    /// <summary>
    /// Employee serial number associated with the user
    /// </summary>
    public int? EmpSerial { get; set; }
}