// <auto-generated />
using System;
using Entities.Models.Databases.PostgresDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20250202115708_AddColorAndIconForModule")]
    partial class AddColorAndIconForModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Tables.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Changes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("changes");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("EmpSerial")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("emp_serial");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<decimal?>("ModuleNo")
                        .HasPrecision(5)
                        .HasColumnType("numeric(5)")
                        .HasColumnName("module_no");

                    b.Property<string>("TableId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_id");

                    b.Property<string>("TableName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("time_stamp");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("control_code")
                        .HasComment("Name of the control");

                    b.Property<string>("ControlDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("control_description")
                        .HasComment("Description of the control");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("PageId")
                        .HasColumnType("integer")
                        .HasColumnName("page_id")
                        .HasComment("Foreign key referencing SEC_PAGES table");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_control_lists");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_sec_control_lists_page_id");

                    b.ToTable("sec_control_lists", null, t =>
                        {
                            t.HasComment("SEC_CONTROLS_LIST table for storing control information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchiveRole")
                        .HasColumnType("integer")
                        .HasColumnName("archive_role")
                        .HasComment("Role for archive permissions");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name")
                        .HasComment("Name of the group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_groups");

                    b.ToTable("sec_groups", null, t =>
                        {
                            t.HasComment("SEC_GROUPS table for storing group information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ControlCode")
                        .HasColumnType("integer")
                        .HasColumnName("control_code")
                        .HasComment("Control code, foreign key referencing SEC_CONTROLS_LIST");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int>("GroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("group_code")
                        .HasComment("Group code, foreign key referencing SEC_GROUPS");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("PageCode")
                        .HasColumnType("integer")
                        .HasColumnName("page_code");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_group_controls");

                    b.HasIndex("ControlCode")
                        .HasDatabaseName("ix_sec_group_controls_control_code");

                    b.HasIndex("PageCode")
                        .HasDatabaseName("ix_sec_group_controls_page_code");

                    b.HasIndex("GroupCode", "ControlCode", "PageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_group_controls_group_code_control_code_page_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("sec_group_controls", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_CONTROLS table for linking groups and controls");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int>("EmpCode")
                        .HasColumnType("integer")
                        .HasColumnName("emp_code")
                        .HasComment("Employee code referencing an employee");

                    b.Property<int>("GroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("group_code")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_group_employees");

                    b.HasIndex("GroupCode", "EmpCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_group_employees_group_code_emp_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("sec_group_employees", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_EMPLOYEES table for linking groups and employees");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int>("GroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("group_code")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("JobCode")
                        .HasColumnType("integer")
                        .HasColumnName("job_code")
                        .HasComment("Job code referencing a job");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_group_jobs");

                    b.HasIndex("GroupCode", "JobCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_group_jobs_group_code_job_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("sec_group_jobs", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_JOBS table for linking groups and jobs");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int>("GroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("group_code")
                        .HasComment("Group code referencing a group");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("PageCode")
                        .HasColumnType("integer")
                        .HasColumnName("page_code")
                        .HasComment("Page ID referencing a page");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_group_pages");

                    b.HasIndex("PageCode")
                        .HasDatabaseName("ix_sec_group_pages_page_code");

                    b.HasIndex("GroupCode", "PageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_group_pages_group_code_page_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("sec_group_pages", null, t =>
                        {
                            t.HasComment("SEC_GROUPS_PAGES table for linking groups and pages");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color")
                        .HasComment("Color of the module");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon")
                        .HasComment("Icon of the module");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("module_name")
                        .HasComment("Name of the module");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_modules");

                    b.ToTable("sec_modules", null, t =>
                        {
                            t.HasComment("SEC_MODULES table for storing module information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModuleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int>("GroupCode")
                        .HasColumnType("integer")
                        .HasColumnName("group_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("integer")
                        .HasColumnName("module_code");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_module_group");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("ix_sec_module_group_module_code");

                    b.HasIndex("GroupCode", "ModuleCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sec_module_group_group_code_module_code")
                        .HasFilter("is_deleted = FALSE");

                    b.ToTable("sec_module_group", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("icon")
                        .HasComment("Icon associated with the page");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("integer")
                        .HasColumnName("module_code")
                        .HasComment("Module number associated with the page");

                    b.Property<string>("PageName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("page_name")
                        .HasComment("Page name in English");

                    b.Property<int?>("PageOrder")
                        .HasColumnType("integer")
                        .HasColumnName("page_order")
                        .HasComment("Order of the page");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("ServiceCode")
                        .HasColumnType("integer")
                        .HasColumnName("service_code");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_pages");

                    b.HasIndex("ModuleCode")
                        .HasDatabaseName("ix_sec_pages_module_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_sec_pages_parent_id");

                    b.HasIndex("ServiceCode")
                        .HasDatabaseName("ix_sec_pages_service_code");

                    b.ToTable("sec_pages", null, t =>
                        {
                            t.HasComment("SEC_PAGES table for storing page details");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("boolean")
                        .HasColumnName("is_taken");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<int?>("ModuleNo")
                        .HasColumnType("integer")
                        .HasColumnName("module_no");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_name")
                        .HasComment("Name of the SERVICES ");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.HasKey("Id")
                        .HasName("pk_sec_services");

                    b.HasIndex("ModuleNo")
                        .HasDatabaseName("ix_sec_services_module_no");

                    b.ToTable("sec_services", null, t =>
                        {
                            t.HasComment("SEC_SERVICES table for storing SERVICES information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delete_date");

                    b.Property<string>("DeleteUserCode")
                        .HasColumnType("text")
                        .HasColumnName("delete_user_code");

                    b.Property<int?>("EmpSerial")
                        .HasColumnType("integer")
                        .HasColumnName("emp_serial")
                        .HasComment("Employee serial number associated with the user");

                    b.Property<DateTime?>("InsertDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("insert_date");

                    b.Property<string>("InsertUserCode")
                        .HasColumnType("text")
                        .HasColumnName("insert_user_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_update");

                    b.Property<string>("Memo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("memo")
                        .HasComment("Additional notes or memo for the user");

                    b.Property<int?>("MtgPersonRole")
                        .HasColumnType("integer")
                        .HasColumnName("mtg_person_role")
                        .HasComment("Role of the person in meetings");

                    b.Property<string>("MtgRelPrsn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mtg_rel_prsn")
                        .HasComment("Related person information for meetings");

                    b.Property<string>("PersonCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("person_code")
                        .HasComment("Code associated with the person");

                    b.Property<string>("Sign")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sign")
                        .HasComment("Digital signature of the user");

                    b.Property<int?>("Signotech")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("signotech")
                        .HasDefaultValueSql("0")
                        .HasComment("Flag for Signotec (default: 0)");

                    b.Property<string>("UpdateUserCode")
                        .HasColumnType("text")
                        .HasColumnName("update_user_code");

                    b.Property<int?>("UserActivation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_activation")
                        .HasDefaultValueSql("1")
                        .HasComment("Activation status of the user (default: 1)");

                    b.Property<string>("UserDesc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_desc")
                        .HasComment("Description of the user");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name")
                        .HasComment("Name of the user");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_password")
                        .HasComment("Encrypted password for the user");

                    b.Property<int?>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no")
                        .HasComment("Version number for the user");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex(new[] { "UserName" }, "USER_NAME_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.HasIndex(new[] { "UserName" }, "USER_NAME_UNIQUE_INDEX")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("USERS table for storing user information");
                        });
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecControlLists")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_control_lists_sec_pages_page_id");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupControl", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecControlList", "SecControlLists")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("ControlCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_controls_sec_control_lists_control_code");

                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroups")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_controls_sec_groups_group_code");

                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecGroupControls")
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_controls_sec_pages_page_code");

                    b.Navigation("SecControlLists");

                    b.Navigation("SecGroups");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupEmployee", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecGroupEmployees")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_employees_sec_groups_group_code");

                    b.Navigation("SecGroup");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupJob", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroups")
                        .WithMany("SecGroupJobs")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_jobs_sec_groups_group_code");

                    b.Navigation("SecGroups");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroupPage", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecGroupPages")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_pages_sec_groups_group_code");

                    b.HasOne("Entities.Models.Tables.SecPage", "SecPage")
                        .WithMany("SecGroupPages")
                        .HasForeignKey("PageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_group_pages_sec_pages_page_code");

                    b.Navigation("SecGroup");

                    b.Navigation("SecPage");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModuleGroup", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecGroup", "SecGroup")
                        .WithMany("SecModuleGroups")
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_module_group_sec_groups_group_code");

                    b.HasOne("Entities.Models.Tables.SecModule", "SecModule")
                        .WithMany("SecModuleGroups")
                        .HasForeignKey("ModuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_module_group_sec_modules_module_code");

                    b.Navigation("SecGroup");

                    b.Navigation("SecModule");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecModule", "SecModule")
                        .WithMany("SecPages")
                        .HasForeignKey("ModuleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sec_pages_sec_modules_module_code");

                    b.HasOne("Entities.Models.Tables.SecPage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sec_pages_sec_pages_parent_id");

                    b.HasOne("Entities.Models.Tables.SecService", "SecService")
                        .WithMany("SecPages")
                        .HasForeignKey("ServiceCode")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sec_pages_sec_services_service_code");

                    b.Navigation("Parent");

                    b.Navigation("SecModule");

                    b.Navigation("SecService");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.HasOne("Entities.Models.Tables.SecModule", "SecModules")
                        .WithMany("SecServices")
                        .HasForeignKey("ModuleNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sec_services_sec_modules_module_no");

                    b.Navigation("SecModules");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecControlList", b =>
                {
                    b.Navigation("SecGroupControls");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecGroup", b =>
                {
                    b.Navigation("SecGroupControls");

                    b.Navigation("SecGroupEmployees");

                    b.Navigation("SecGroupJobs");

                    b.Navigation("SecGroupPages");

                    b.Navigation("SecModuleGroups");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecModule", b =>
                {
                    b.Navigation("SecModuleGroups");

                    b.Navigation("SecPages");

                    b.Navigation("SecServices");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecPage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SecControlLists");

                    b.Navigation("SecGroupControls");

                    b.Navigation("SecGroupPages");
                });

            modelBuilder.Entity("Entities.Models.Tables.SecService", b =>
                {
                    b.Navigation("SecPages");
                });
#pragma warning restore 612, 618
        }
    }
}
