// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;


#nullable disable

namespace Entities.Models.Configurations
{
    public partial class SecControlListConfiguration : IEntityTypeConfiguration<SecControlList>
    {
        public void Configure(EntityTypeBuilder<SecControlList> entity)
        {

        }

        partial void OnConfigurePartial(EntityTypeBuilder<SecControlList> entity);
    }
}
