// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Entities.Models.Configurations;

public partial class SecGroupConfiguration : IEntityTypeConfiguration<SecGroup>
{
    public void Configure(EntityTypeBuilder<SecGroup> entity)
    {

    }

    partial void OnConfigurePartial(EntityTypeBuilder<SecGroup> entity);
}
