// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;

#nullable disable

namespace Entities.Models.Configurations
{
    public partial class SecPageConfiguration : IEntityTypeConfiguration<SecPage>
    {
        public void Configure(EntityTypeBuilder<SecPage> entity)
        {

        }

        partial void OnConfigurePartial(EntityTypeBuilder<SecPage> entity);
    }
}
