// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Entities.Models.BaseConfiguration;


#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations;

public  class SecControlListConfiguration : BaseConfiguration<SecControlList>
{
    public override void Configure(EntityTypeBuilder<SecControlList> entity)
    {
        base.Configure(entity);


        entity.HasComment("SEC_CONTROLS_LIST table for storing control information");



        entity.Property(e => e.ControlDescription)
            .HasMaxLength(200)
            .HasComment("Description of the control");

        entity.Property(e => e.ControlCode)
            .HasMaxLength(200)
            .HasComment("Name of the control");

        entity.Property(e => e.PageId).HasComment("Foreign key referencing SEC_PAGES table");
        entity.HasIndex(e => new { e.ControlCode })
       .IsUnique().HasFilter("is_deleted = FALSE"); ;
        entity.HasOne(d => d.SecPage)
            .WithMany(p => p.SecControlLists)
            .HasForeignKey(d => d.PageId)
            .OnDelete(DeleteBehavior.Restrict);

    }

}
