// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations;

public partial class SecGroupJobConfiguration : BaseConfiguration<SecGroupJob>
{
    public override void Configure(EntityTypeBuilder<SecGroupJob> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_GROUPS_JOBS table for linking groups and jobs");

        entity.HasIndex(e => new { e.GroupCode, e.JobCode })
        .IsUnique().HasFilter("is_deleted = FALSE"); ;



        entity.Property(e => e.GroupCode).HasComment("Group code referencing a group");

        entity.Property(e => e.JobCode).HasComment("Job code referencing a job");

        entity.HasOne(d => d.SecGroups)
            .WithMany(p => p.SecGroupJobs)
            .HasForeignKey(d => d.GroupCode)
            .OnDelete(DeleteBehavior.Restrict);

    }

}
