// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations
{
    public  class SecGroupConfiguration : BaseConfiguration<SecGroup>
    {
        public override void Configure(EntityTypeBuilder<SecGroup> entity)
        {


            base.Configure(entity);     

            entity.HasComment("SEC_GROUPS table for storing group information");




            entity.Property(e => e.ArchiveRole).HasComment("Role for archive permissions");

            entity.Property(e => e.GroupName)
                .HasMaxLength(200)
                .HasComment("Name of the group");





            //entity.Property(e => e.UnitCode)
            //    .HasMaxLength(10)
            //    .HasComment("Unit code associated with the group");

            entity.HasMany(d => d.SecGroupEmployees)
                .WithOne(p => p.SecGroup)
                .HasForeignKey(d => d.GroupCode).OnDelete(DeleteBehavior.Restrict);
        }

    }

}


