// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations;

public  class SecGroupEmployeeConfiguration : BaseConfiguration<SecGroupEmployee>
{
    public override void Configure(EntityTypeBuilder<SecGroupEmployee> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_GROUPS_EMPLOYEES table for linking groups and employees");

        entity.HasIndex(e => new { e.GroupCode, e.EmpCode })
            .IsUnique().HasFilter("is_deleted = FALSE"); ;



        entity.Property(e => e.EmpCode).HasComment("Employee code referencing an employee");

        entity.Property(e => e.GroupCode).HasComment("Group code referencing a group");

    }

}
