// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations;

public class SecGroupPageConfiguration : BaseConfiguration<SecGroupPage>
{
    public override void Configure(EntityTypeBuilder<SecGroupPage> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_GROUPS_PAGES table for linking groups and pages");


        entity.HasIndex(e => new { e.GroupCode, e.PageCode })
      .IsUnique().HasFilter("is_deleted = FALSE"); ;


        entity.Property(e => e.GroupCode).HasComment("Group code referencing a group");

        entity.Property(e => e.PageCode).HasComment("Page ID referencing a page");

        entity.HasOne(d => d.SecGroup)
            .WithMany(p => p.SecGroupPages)
            .HasForeignKey(d => d.GroupCode)
            .OnDelete(DeleteBehavior.Restrict);

        entity.HasOne(d => d.SecPage)
            .WithMany(p => p.SecGroupPages)
            .HasForeignKey(d => d.PageCode)
            .OnDelete(DeleteBehavior.Restrict);

    }

}
