// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Entities.Models.Tables;

using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System;
using Entities.Models.BaseConfiguration;

#nullable disable

namespace Entities.Models.Databases.PostgresDb.Configurations;

public class SecPageConfiguration : BaseConfiguration<SecPage>
{
    public override void Configure(EntityTypeBuilder<SecPage> entity)
    {

        base.Configure(entity);

        entity.HasComment("SEC_PAGES table for storing page details");



        entity.Property(e => e.Icon)
            .HasMaxLength(200)
            .HasComment("Icon associated with the page");
        entity.Property(e => e.PageUrl)
            .HasMaxLength(200)
            .HasComment("Url associated with the page");

        entity.Property(e => e.ModuleCode).HasComment("Module number associated with the page");

        entity.Property(e => e.PageName)
            .HasMaxLength(100)
            .HasComment("Page name in English");

        entity.HasIndex(e => new { e.PageOrder,e.ModuleCode })
            .IsUnique().HasFilter("is_deleted = FALSE"); ;

        entity.HasOne(d => d.SecService)
            .WithMany(p => p.SecPages)
            .HasForeignKey(d => d.ServiceCode)
            .OnDelete(DeleteBehavior.SetNull);

        entity.HasOne(d => d.SecModule)
             .WithMany(p => p.SecPages)
             .HasForeignKey(d => d.ModuleCode)
             .OnDelete(DeleteBehavior.Restrict);

        entity.HasMany(d => d.Children)
        .WithOne(p => p.Parent)
        .HasForeignKey(d => d.ParentId)
        .OnDelete(DeleteBehavior.Restrict);

        entity.Property(e => e.PageOrder).HasComment("Order of the page");



    }

}
